name: geo
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5
  - _python_abi3_support=1.0
  - affine=2.4.0
  - anyio=4.11.0
  - anywidget=0.9.21
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - arro3-compute=0.6.5
  - arro3-core=0.6.5
  - arro3-io=0.6.5
  - arrow=1.4.0
  - asttokens=3.0.0
  - async-lru=2.0.5
  - attrs=25.4.0
  - aws-c-auth=0.9.1
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.4
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.6
  - aws-c-http=0.10.4
  - aws-c-io=0.22.0
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.8.6
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.34.3
  - aws-sdk-cpp=1.11.606
  - azure-core-cpp=1.16.0
  - azure-identity-cpp=1.12.0
  - azure-storage-blobs-cpp=12.14.0
  - azure-storage-common-cpp=12.10.0
  - babel=2.17.0
  - beautifulsoup4=4.14.2
  - bleach=6.2.0
  - blosc=1.21.6
  - branca=0.8.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.10.5
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - capnproto=1.2.0
  - ceres-solver=2.2.0
  - certifi=2025.10.5
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - click=8.3.0
  - click-plugins=1.1.1.2
  - cligj=0.7.2
  - colorama=0.4.6
  - comm=0.2.3
  - contourpy=1.3.3
  - cpython=3.12.12
  - cuda-cudart=12.9.79
  - cuda-cudart_win-64=12.9.79
  - cuda-nvrtc=12.9.86
  - cuda-version=12.9
  - cycler=0.12.1
  - debugpy=1.8.17
  - decorator=5.2.1
  - defusedxml=0.7.1
  - docutils=0.22.3
  - double-conversion=3.3.1
  - draco=1.5.7
  - eigen=3.4.0
  - entrypoints=0.4
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - fiona=1.10.1
  - fmt=11.2.0
  - folium=0.20.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.60.1
  - fqdn=1.5.1
  - freetype=2.14.1
  - freexl=2.0.0
  - gdal=3.10.3
  - geoarrow-rust-core=0.5.3
  - geopandas=1.1.1
  - geopandas-base=1.1.1
  - geos=3.14.0
  - geotiff=1.7.4
  - gflags=2.2.2
  - glog=0.7.1
  - gmp=6.3.0
  - graphite2=1.3.14
  - h11=0.16.0
  - h2=4.3.0
  - harfbuzz=12.2.0
  - hdf5=1.14.6
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - importlib-metadata=8.7.0
  - ipykernel=7.1.0
  - ipython=9.7.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.8
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.2
  - json5=0.12.1
  - jsonpointer=3.0.0
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.9.1
  - jsonschema-with-format-nongpl=4.25.1
  - jupyter-lsp=2.3.0
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - jupyter_events=0.12.0
  - jupyter_server=2.17.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.10
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.28.0
  - jupyterlab_widgets=3.0.16
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lark=1.3.1
  - laspy=2.6.1
  - lazrs-python=0.8.0
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20250512.1
  - libaec=1.1.4
  - libamd=3.3.3
  - libarchive=3.8.1
  - libarrow=20.0.0
  - libarrow-acero=20.0.0
  - libarrow-dataset=20.0.0
  - libarrow-substrait=20.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libbtf=2.3.2
  - libcamd=3.3.3
  - libcblas=3.9.0
  - libccolamd=3.3.4
  - libcholmod=5.3.1
  - libclang13=21.1.5
  - libcolamd=3.3.4
  - libcrc32c=1.1.2
  - libcublas=12.9.1.4
  - libcurl=8.17.0
  - libcusolver=11.7.5.82
  - libcusparse=12.5.10.65
  - libcxsparse=4.4.1
  - libdeflate=1.24
  - libevent=2.1.12
  - libexpat=2.7.1
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgdal-arrow-parquet=3.10.3
  - libgdal-core=3.10.3
  - libgdal-hdf5=3.10.3
  - libgdal-pg=3.10.3
  - libgdal-postgisraster=3.10.3
  - libgdal-tiledb=3.10.3
  - libglib=2.86.1
  - libgomp=15.2.0
  - libgoogle-cloud=2.39.0
  - libgoogle-cloud-storage=2.39.0
  - libgrpc=1.73.1
  - libhwloc=2.12.1
  - libiconv=1.18
  - libintl=0.22.5
  - libjpeg-turbo=3.1.2
  - libklu=2.3.5
  - libkml=1.3.0
  - liblapack=3.9.0
  - libldl=3.3.2
  - liblzma=5.8.1
  - libnvjitlink=12.9.86
  - libparquet=20.0.0
  - libparu=1.0.0
  - libpdal=2.8.4
  - libpdal-arrow=2.8.4
  - libpdal-core=2.8.4
  - libpdal-draco=2.8.4
  - libpdal-e57=2.8.4
  - libpdal-hdf=2.8.4
  - libpdal-icebridge=2.8.4
  - libpdal-nitf=2.8.4
  - libpdal-pgpointcloud=2.8.4
  - libpdal-tiledb=2.8.4
  - libpdal-trajectory=2.8.4
  - libpng=1.6.50
  - libpq=17.6
  - libprotobuf=6.31.1
  - librbio=4.3.4
  - libre2-11=2025.11.05
  - librttopo=1.1.0
  - libsodium=1.0.20
  - libspatialindex=2.1.0
  - libspatialite=5.1.0
  - libspex=3.2.3
  - libspqr=4.3.4
  - libsqlite=3.51.0
  - libssh2=1.11.1
  - libsuitesparseconfig=7.10.1
  - libthrift=0.22.0
  - libtiff=4.7.1
  - libumfpack=6.3.5
  - libutf8proc=2.11.0
  - libvulkan-loader=1.4.328.1
  - libwebp-base=1.6.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxcb=1.17.0
  - libxml2=2.13.9
  - libxslt=1.1.43
  - libzlib=1.3.1
  - llvm-openmp=21.1.5
  - lonboard=0.13.0
  - lxml=6.0.2
  - lz4-c=1.10.0
  - lzo=2.10
  - m2r2=0.3.4
  - mapclassify=2.10.0
  - markupsafe=3.0.3
  - matplotlib=3.10.7
  - matplotlib-base=3.10.7
  - matplotlib-inline=0.2.1
  - metis=5.1.0
  - minizip=4.0.10
  - mistune=0.8.4
  - mkl=2025.3.0
  - mpfr=4.2.1
  - munkres=1.1.4
  - nbclient=0.10.2
  - nbconvert-core=6.5.3
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - networkx=3.5
  - nitro=2.7.dev8
  - notebook-shim=0.2.4
  - numpy=2.3.4
  - openjpeg=2.5.4
  - openssl=3.5.4
  - orc=2.2.0
  - osmnx=2.0.7
  - osmnx-base=2.0.7
  - overrides=7.7.0
  - packaging=25.0
  - pandas=2.3.3
  - pandocfilters=1.5.0
  - parso=0.8.5
  - pcre2=10.46
  - pdal=2.8.4
  - pillow=12.0.0
  - pip=25.2
  - pixman=0.46.4
  - platformdirs=4.5.0
  - postgresql=17.6
  - proj=9.6.2
  - prometheus_client=0.23.1
  - prompt-toolkit=3.0.52
  - psutil=7.1.3
  - psygnal=0.15.0
  - pthread-stubs=0.4
  - pure_eval=0.2.3
  - pyarrow=20.0.0
  - pyarrow-core=20.0.0
  - pycparser=2.22
  - pygments=2.19.2
  - pyogrio=0.11.0
  - pyparsing=3.2.5
  - pyproj=3.7.2
  - pyside6=6.9.2
  - pysocks=1.7.1
  - python=3.12.12
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.2
  - python-gil=3.12.12
  - python-json-logger=2.0.7
  - python-pdal=3.4.5
  - python-tzdata=2025.2
  - python_abi=3.12
  - pytz=2025.2
  - pywin32=311
  - pywinpty=2.0.15
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qhull=2020.2
  - qt6-main=6.9.2
  - rasterio=1.4.3
  - re2=2025.11.05
  - referencing=0.37.0
  - requests=2.32.5
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - rio-vrt=0.3.1
  - rpds-py=0.28.0
  - rtree=1.4.1
  - scikit-learn=1.7.2
  - scipy=1.16.3
  - send2trash=1.8.3
  - setuptools=80.9.0
  - shapely=2.1.2
  - six=1.17.0
  - snappy=1.2.2
  - sniffio=1.3.1
  - snuggs=1.4.7
  - soupsieve=2.8
  - spdlog=1.15.3
  - sqlite=3.51.0
  - stack_data=0.6.3
  - suitesparse=7.10.1
  - tbb=2022.3.0
  - terminado=0.18.1
  - threadpoolctl=3.6.0
  - tiledb=2.28.1
  - tinycss2=1.4.0
  - tk=8.6.13
  - tomli=2.3.0
  - tornado=6.5.2
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - typing_utils=0.1.0
  - tzdata=2025b
  - ucrt=10.0.26100.0
  - unicodedata2=17.0.0
  - uri-template=1.3.0
  - uriparser=0.9.8
  - urllib3=2.5.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vcomp14=14.44.35208
  - vs2015_runtime=14.44.35208
  - wcwidth=0.2.14
  - webcolors=25.10.0
  - webencodings=0.5.1
  - websocket-client=1.9.0
  - wheel=0.45.1
  - widgetsnbextension=4.0.15
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - wrapt=2.0.1
  - xerces-c=3.2.5
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xyzservices=2025.10.0
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zlib-ng=2.2.5
  - zstandard=0.25.0
  - zstd=1.5.7

prefix: "C:\\Users\\laval\\miniforge3\\envs\\geo"
